### ISSUE TITLE
Why I can't use this library on eclipse

### ISSUE THREAD

**Issue by abc2005** [Todd-Davies/ProgressWheel#46]
hello
I tried to import this library in eclipse , I right click and import it as android project .On the properties , the "is library" is checked .

The problem is ,in the main.java and ProgressWheel.java , every "R" has this error "R cannot be resolved to a variable"   . For instance , this line has the problem "R.styleable.ProgressWheel" . 

What is the problem ?Why I can't import it ? 

Looking to hear from you
King Regards

**Comment by Todd-Davies** [comment]
This library should work fine with eclipse. Unfortunately, I don't use it as an IDE anymore, so I won't be much help, however, I do remember that Android resources could be a pain with libraries/imports, I think it's a more generic problem rather than one specific to this project.

Try asking on StackOverflow or somewhere.

Thanks, and good luck!
