### ISSUE TITLE
barLength conflicts

### ISSUE THREAD

**Issue by LyndonChin** [Todd-Davies/ProgressWheel#66]
The `barLength` property is conflicting with the android SDK

**Comment by Pedroalexandrelopes** [comment]
Same here...

**Comment by rliuzzi** [comment]
Hey guys this already fixed, just there isn't a release yet. Could be sooo nice to have a release :)

**Comment by LyndonChin** [comment]
@krislq 👍

**Comment by LuxxxLucy** [comment]
@rliuzzi how did you manage to solve that conflict?

**Comment by rliuzzi** [comment]
hey @LuxxxLucy 

This issue was solved with these commits by @vicktor  but they are not included in the latest release:
https://github.com/Todd-Davies/ProgressWheel/commit/65cefa324c329417f0fecccebae4a2ffd06468c8
https://github.com/Todd-Davies/ProgressWheel/commit/61cfba9d57e11f0ff0da93a290871fde2ecff065
https://github.com/Todd-Davies/ProgressWheel/commit/cec6f03262c5f869d0b2c8934d643ed848fb9747
https://github.com/Todd-Davies/ProgressWheel/commit/23c3bdd790275bef1f7e95604bce03ab4896be77

Since this project is open source I just pulled from master and included the project as a module in android studio. It could be so much easier if it was released and we could just include the version with gradle... 🐹

**Comment by Todd-Davies** [comment]
I think it's in the latest release here: https://github.com/Todd-Davies/ProgressWheel/releases/tag/1.2

Is there somewhere else I should release it?

**Comment by rliuzzi** [comment]
Hey @Todd-Davies , I am not sure I saw you accepted the PR and it should be included in the latest release but when I tried it, it still wasn't working there.

**Comment by Orbycius** [comment]
Hi all,

Just wanted to confirm that I have upgraded to 1.2 using gradle (compile 'com.github.Todd-Davies:ProgressWheel:1.2') and first thing I got was an error to switch from the old attributes to the new ones with the 'pw' prefix so everything seems fine.

**Comment by rliuzzi** [comment]
You are right I also tested and it is fixed in the latest release so I think this issue can be closed ;)

**Comment by LuxxxLucy** [comment]
thx！！！it is solved！
